@{
    # ---------------------------------------------------------------------------
    # Overlay manifest — single source of truth for the SSIS Copilot Toolkit.
    #
    # Consumed by:
    #   install\Add-CopilotSsisToolkit.ps1     (brownfield: drop overlay into existing repo)
    #   .github\workflows\template-cleanup.yml (greenfield: strip demo content on first push)
    #
    # Conventions:
    #   - Paths are repo-relative, forward-slash.
    #   - "overlay"   = files copied by the brownfield installer; survive template cleanup.
    #   - "demo"      = files present in the template only; stripped by template cleanup;
    #                   never copied by the brownfield installer.
    #   - "ignore"    = files that must never ship — debug detritus or build artifacts.
    # ---------------------------------------------------------------------------

    Version = '0.1.0'

    Overlay = @(
        # Repo-root invariants
        @{ Path = '.gitattributes'; Action = 'CopyIfMissing' }
        @{ Path = '.gitignore';     Action = 'AppendBlock' }
        @{ Path = 'AGENTS.md';      Action = 'AppendBlock' }

        # GitHub Copilot customizations — work in both Visual Studio 2026 18.4+ and VS Code Copilot Chat
        @{ Path = '.github/copilot-instructions.md'; Action = 'Copy' }
        @{ Path = '.github/agents';                  Action = 'CopyDir' }
        @{ Path = '.github/instructions';            Action = 'CopyDir' }
        @{ Path = '.github/prompts';                 Action = 'CopyDir' }
        @{ Path = '.github/skills';                  Action = 'CopyDir' }

        # VS Code workspace affordances (ignored by Visual Studio, harmless if present)
        @{ Path = '.vscode/extensions.json'; Action = 'CopyIfMissing' }
        @{ Path = '.vscode/tasks.json';      Action = 'CopyIfMissing' }
        @{ Path = '.vscode/mcp.json';        Action = 'CopyIfMissing' }

        # PowerShell primitives — the only thing the agents actually invoke at runtime
        @{ Path = 'tools/README.md';                                 Action = 'Copy' }
        @{ Path = 'tools/New-SsisPackage.ps1';                       Action = 'Copy' }
        @{ Path = 'tools/Test-SsisPackage.ps1';                      Action = 'Copy' }
        @{ Path = 'tools/Test-SsisDesignerLoad.ps1';                 Action = 'Copy' }
        @{ Path = 'tools/lib/SsisOm.psm1';                           Action = 'Copy' }
        @{ Path = 'tools/lib/patterns';                              Action = 'CopyDir' }
        @{ Path = 'tools/lib/SsisOmHost/Build-SsisOmHost.ps1';       Action = 'Copy' }
        @{ Path = 'tools/lib/SsisOmHost/MetadataHelpers.cs';         Action = 'Copy' }
        @{ Path = 'tools/lib/SsisOmHost/PackageBuilder.cs';          Action = 'Copy' }
        @{ Path = 'tools/lib/SsisOmHost/Program.cs';                 Action = 'Copy' }
        @{ Path = 'tools/lib/SsisOmHost/Patterns';                   Action = 'CopyDir' }
    )

    Demo = @(
        # SQL Server + SSISDB provisioning for the AdventureWorks2025 walkthrough
        @{ Path = 'install/Install-Toolkit.ps1' }

        # AdventureWorks2025 demo content
        @{ Path = 'templates/sql' }
        @{ Path = 'templates/metadata' }
        @{ Path = 'templates/ssis-project' }
        @{ Path = 'templates/docs' }

        # Demo script — specific to building this toolkit, not consuming it
        @{ Path = 'context' }

        # README is template-only; brownfield repos keep their own README.
        # The installer appends a section to the target's AGENTS.md instead.
        # The template-cleanup workflow generates a fresh brownfield-style README.
        @{ Path = 'README.md' }

        # Greenfield first-push workflow — strips this Demo list, then deletes itself.
        # Must be in Demo (not Overlay) so the brownfield installer never copies it.
        @{ Path = '.github/workflows/template-cleanup.yml' }
    )

    # Files that must never ship in either mode. Listed here so a "release lint"
    # check can fail the build if any of them appear in HEAD.
    Ignore = @(
        # Debug artifacts from the Lookup E_UNEXPECTED investigation
        'tools/_probe.cs'
        'tools/_probe.exe'
        'tools/_probe.ps1'
        'tools/_probe2.ps1'
        'tools/_probe3.ps1'
        'tools/_probe4.ps1'
        'tools/lib/SsisOmHost/LookupMinRepro.dtsx'
        'tools/lib/SsisOmHost/LookupMinRepro_TEST.dtsx'
        'tools/lib/SsisOmHost/LookupMinRepro_TEST2.dtsx'
        'tools/lib/SsisOmHost/_lookup_minrepro.cs'
        'tools/lib/SsisOmHost/_lookup_minrepro.exe'
        'tools/lib/SsisOmHost/_validate_probe.cs'
        'tools/lib/SsisOmHost/_validate_probe.exe'
        'tools/lib/SsisOmHost/_dtexec_full.log'

        # Build outputs — regenerated by tools/lib/SsisOmHost/Build-SsisOmHost.ps1
        'tools/lib/SsisOmHost/SsisOmHost.dll'
        'tools/lib/SsisOmHost/SsisOmHost.exe'

        # Stray files
        'Dim_Customer_Type1_TEST.dtsx'
        'System.Management.Automation.PSReference`1[System.String]'
    )

    # Block of text appended to AGENTS.md in the target repo. Wrapped in HTML
    # comments so the installer can find it again on upgrade and replace in place
    # without duplicating.
    AgentsMdBlock = @'
<!-- BEGIN: ssis-copilot-toolkit (managed; do not edit between markers) -->
## SSIS Copilot Toolkit

This repo has the [SSIS Copilot Toolkit](https://github.com/<owner>/<repo>) overlay installed.

- The custom agent `@ssis-author` is the only sanctioned entry point for SSIS work.
- Hand-editing `.dtsx`, `.dtproj`, `.conmgr`, or `.params` is forbidden — packages regenerate from metadata JSON.
- Every SSIS change must pass the [`ssis-delivery-gate`](.github/skills/ssis-delivery-gate/SKILL.md) skill (run by `@ssis-validator`).
- Detailed conventions live in [`.github/copilot-instructions.md`](.github/copilot-instructions.md).

Works in Visual Studio 2026 (18.4+) and VS Code with GitHub Copilot Chat.
<!-- END: ssis-copilot-toolkit -->
'@

    # Block of text appended to .gitignore. Same wrapping convention as AGENTS.md.
    GitignoreBlock = @'
# BEGIN: ssis-copilot-toolkit (managed; do not edit between markers)
# Build outputs from the managed-OM host
tools/lib/SsisOmHost/SsisOmHost.dll
tools/lib/SsisOmHost/SsisOmHost.exe
tools/lib/SsisOmHost/bin/
tools/lib/SsisOmHost/obj/

# SSIS build outputs
**/bin/
**/obj/
*.ispac

# SSISDB execution logs
**/SSIS.Replay/
**/*.dtsx.log
# END: ssis-copilot-toolkit
'@
}
